
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun May 30 15:55:28 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 23;
  public static final int CONST = 8;
  public static final int GE = 33;
  public static final int CASE = 20;
  public static final int LPAREN = 44;
  public static final int SEMI = 41;
  public static final int CONTINUE = 19;
  public static final int MINUS = 26;
  public static final int RPAREN = 45;
  public static final int AND = 36;
  public static final int LT = 34;
  public static final int OR = 37;
  public static final int QMARK = 50;
  public static final int COMMA = 42;
  public static final int CLASS = 5;
  public static final int INC = 39;
  public static final int DIV = 28;
  public static final int PLUS = 25;
  public static final int ASSIGN = 38;
  public static final int IF = 9;
  public static final int DOT = 43;
  public static final int LE = 35;
  public static final int DOTS = 51;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int EQUAL = 30;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int MUL = 27;
  public static final int MOD = 29;
  public static final int BREAK = 4;
  public static final int IDENT = 21;
  public static final int VOID = 17;
  public static final int ERROR = 2;
  public static final int SWITCH = 10;
  public static final int LBRACE = 48;
  public static final int ELSE = 7;
  public static final int LSQUARE = 46;
  public static final int ENUM = 6;
  public static final int READ = 15;
  public static final int RSQUARE = 47;
  public static final int WHILE = 12;
  public static final int NEQUAL = 31;
  public static final int RBRACE = 49;
  public static final int EXTENDS = 18;
  public static final int PROG = 3;
  public static final int BOOL_CONST = 24;
  public static final int DEC = 40;
  public static final int GT = 32;
  public static final int PRINT = 14;
  public static final int DO = 11;
  public static final int NUMBER_CONST = 22;
}

